Insert into T_JSTREE_COMPARE_INFO
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    TOP_IMAGE_URL_1, TOP_IMAGE_URL_2, TOP_IMAGE_URL_3, TOP_VENDER_URL , TOP_VENDER_TEXT,
    TOP_POST1_ICON , TOP_POST1_URL  , TOP_POST1_TEXT , TOP_POST2_ICON , TOP_POST2_URL  , TOP_POST2_TEXT ,
    TOP_POST3_ICON , TOP_POST3_URL  , TOP_POST3_TEXT , TOP_POST4_ICON , TOP_POST4_URL  , TOP_POST4_TEXT ,
    TOP_POST5_ICON , TOP_POST5_URL  , TOP_POST5_TEXT ,
    MID_IMAGE_URL_1, MID_IMAGE_URL_2, MID_IMAGE_URL_3, MID_VENDER_URL , MID_VENDER_TEXT,
    MID_POST1_ICON , MID_POST1_URL  , MID_POST1_TEXT , MID_POST2_ICON , MID_POST2_URL  , MID_POST2_TEXT ,
    MID_POST3_ICON , MID_POST3_URL  , MID_POST3_TEXT , MID_POST4_ICON , MID_POST4_URL  , MID_POST4_TEXT ,
    MID_POST5_ICON , MID_POST5_URL  , MID_POST5_TEXT ,
    BOT_IMAGE_URL_1, BOT_IMAGE_URL_2, BOT_IMAGE_URL_3, BOT_VENDER_URL , BOT_VENDER_TEXT,
    BOT_POST1_ICON , BOT_POST1_URL  , BOT_POST1_TEXT , BOT_POST2_ICON , BOT_POST2_URL  , BOT_POST2_TEXT ,
    BOT_POST3_ICON , BOT_POST3_URL  , BOT_POST3_TEXT , BOT_POST4_ICON , BOT_POST4_URL  , BOT_POST4_TEXT ,
    BOT_POST5_ICON , BOT_POST5_URL  , BOT_POST5_TEXT )
Values
  ( 1, 0, 0, 1, 8, 0, 'Root Node', 'root',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text');

Insert into T_JSTREE_COMPARE_INFO
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    TOP_IMAGE_URL_1, TOP_IMAGE_URL_2, TOP_IMAGE_URL_3, TOP_VENDER_URL , TOP_VENDER_TEXT,
    TOP_POST1_ICON , TOP_POST1_URL  , TOP_POST1_TEXT , TOP_POST2_ICON , TOP_POST2_URL  , TOP_POST2_TEXT ,
    TOP_POST3_ICON , TOP_POST3_URL  , TOP_POST3_TEXT , TOP_POST4_ICON , TOP_POST4_URL  , TOP_POST4_TEXT ,
    TOP_POST5_ICON , TOP_POST5_URL  , TOP_POST5_TEXT ,
    MID_IMAGE_URL_1, MID_IMAGE_URL_2, MID_IMAGE_URL_3, MID_VENDER_URL , MID_VENDER_TEXT,
    MID_POST1_ICON , MID_POST1_URL  , MID_POST1_TEXT , MID_POST2_ICON , MID_POST2_URL  , MID_POST2_TEXT ,
    MID_POST3_ICON , MID_POST3_URL  , MID_POST3_TEXT , MID_POST4_ICON , MID_POST4_URL  , MID_POST4_TEXT ,
    MID_POST5_ICON , MID_POST5_URL  , MID_POST5_TEXT ,
    BOT_IMAGE_URL_1, BOT_IMAGE_URL_2, BOT_IMAGE_URL_3, BOT_VENDER_URL , BOT_VENDER_TEXT,
    BOT_POST1_ICON , BOT_POST1_URL  , BOT_POST1_TEXT , BOT_POST2_ICON , BOT_POST2_URL  , BOT_POST2_TEXT ,
    BOT_POST3_ICON , BOT_POST3_URL  , BOT_POST3_TEXT , BOT_POST4_ICON , BOT_POST4_URL  , BOT_POST4_TEXT ,
    BOT_POST5_ICON , BOT_POST5_URL  , BOT_POST5_TEXT )
Values
  ( 2, 1, 0, 2, 7, 1, 'First Child', 'drive',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text');

Insert into T_JSTREE_COMPARE_INFO
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    TOP_IMAGE_URL_1, TOP_IMAGE_URL_2, TOP_IMAGE_URL_3, TOP_VENDER_URL , TOP_VENDER_TEXT,
    TOP_POST1_ICON , TOP_POST1_URL  , TOP_POST1_TEXT , TOP_POST2_ICON , TOP_POST2_URL  , TOP_POST2_TEXT ,
    TOP_POST3_ICON , TOP_POST3_URL  , TOP_POST3_TEXT , TOP_POST4_ICON , TOP_POST4_URL  , TOP_POST4_TEXT ,
    TOP_POST5_ICON , TOP_POST5_URL  , TOP_POST5_TEXT ,
    MID_IMAGE_URL_1, MID_IMAGE_URL_2, MID_IMAGE_URL_3, MID_VENDER_URL , MID_VENDER_TEXT,
    MID_POST1_ICON , MID_POST1_URL  , MID_POST1_TEXT , MID_POST2_ICON , MID_POST2_URL  , MID_POST2_TEXT ,
    MID_POST3_ICON , MID_POST3_URL  , MID_POST3_TEXT , MID_POST4_ICON , MID_POST4_URL  , MID_POST4_TEXT ,
    MID_POST5_ICON , MID_POST5_URL  , MID_POST5_TEXT ,
    BOT_IMAGE_URL_1, BOT_IMAGE_URL_2, BOT_IMAGE_URL_3, BOT_VENDER_URL , BOT_VENDER_TEXT,
    BOT_POST1_ICON , BOT_POST1_URL  , BOT_POST1_TEXT , BOT_POST2_ICON , BOT_POST2_URL  , BOT_POST2_TEXT ,
    BOT_POST3_ICON , BOT_POST3_URL  , BOT_POST3_TEXT , BOT_POST4_ICON , BOT_POST4_URL  , BOT_POST4_TEXT ,
    BOT_POST5_ICON , BOT_POST5_URL  , BOT_POST5_TEXT )
Values
  ( 3, 2, 0, 3, 4, 2, 'Leaf Node', 'default',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text');

Insert into T_JSTREE_COMPARE_INFO
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    TOP_IMAGE_URL_1, TOP_IMAGE_URL_2, TOP_IMAGE_URL_3, TOP_VENDER_URL , TOP_VENDER_TEXT,
    TOP_POST1_ICON , TOP_POST1_URL  , TOP_POST1_TEXT , TOP_POST2_ICON , TOP_POST2_URL  , TOP_POST2_TEXT ,
    TOP_POST3_ICON , TOP_POST3_URL  , TOP_POST3_TEXT , TOP_POST4_ICON , TOP_POST4_URL  , TOP_POST4_TEXT ,
    TOP_POST5_ICON , TOP_POST5_URL  , TOP_POST5_TEXT ,
    MID_IMAGE_URL_1, MID_IMAGE_URL_2, MID_IMAGE_URL_3, MID_VENDER_URL , MID_VENDER_TEXT,
    MID_POST1_ICON , MID_POST1_URL  , MID_POST1_TEXT , MID_POST2_ICON , MID_POST2_URL  , MID_POST2_TEXT ,
    MID_POST3_ICON , MID_POST3_URL  , MID_POST3_TEXT , MID_POST4_ICON , MID_POST4_URL  , MID_POST4_TEXT ,
    MID_POST5_ICON , MID_POST5_URL  , MID_POST5_TEXT ,
    BOT_IMAGE_URL_1, BOT_IMAGE_URL_2, BOT_IMAGE_URL_3, BOT_VENDER_URL , BOT_VENDER_TEXT,
    BOT_POST1_ICON , BOT_POST1_URL  , BOT_POST1_TEXT , BOT_POST2_ICON , BOT_POST2_URL  , BOT_POST2_TEXT ,
    BOT_POST3_ICON , BOT_POST3_URL  , BOT_POST3_TEXT , BOT_POST4_ICON , BOT_POST4_URL  , BOT_POST4_TEXT ,
    BOT_POST5_ICON , BOT_POST5_URL  , BOT_POST5_TEXT )
Values
  ( 4, 2, 1, 5, 6, 2, 'Branch Node', 'folder',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text',
    'http', 'http', 'http', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text', 'icon', 'http', 'text',
    'icon', 'http', 'text');
COMMIT;