Insert into T_DIRECT_CHAT
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    MENU_ID, USER_ID, USER_LEVEL, WRITE_TIME, SELECTED_COMPARE_ITEM, CONTENTS_BODY,
    HASH_TAGS, LIKE_COUNT, HATE_COUNT, HIDDEN_YN, REPORT_YN )
Values
  ( 1, 0, 0, 1, 8, 0, 'Root Node', 'root',
    3, 'rootID', 313, '2017-03-13 13:31:33', 3, '글내용',
    '해시태그들', 31, 13, 'show', 'N');
Insert into T_DIRECT_CHAT
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    MENU_ID, USER_ID, USER_LEVEL, WRITE_TIME, SELECTED_COMPARE_ITEM, CONTENTS_BODY,
    HASH_TAGS, LIKE_COUNT, HATE_COUNT, HIDDEN_YN, REPORT_YN )
Values
  ( 2, 1, 0, 2, 7, 1, 'First Child', 'drive',
    3, 'rootID', 313, '2017-03-13 13:31:33', 3, '글내용',
    '해시태그들', 31, 13, 'show', 'N');
Insert into T_DIRECT_CHAT
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    MENU_ID, USER_ID, USER_LEVEL, WRITE_TIME, SELECTED_COMPARE_ITEM, CONTENTS_BODY,
    HASH_TAGS, LIKE_COUNT, HATE_COUNT, HIDDEN_YN, REPORT_YN )
Values
  ( 3, 2, 0, 3, 4, 2, 'Leaf Node', 'default',
    3, 'rootID', 313, '2017-03-13 13:31:33', 3, '글내용',
    '해시태그들', 31, 13, 'show', 'N');
Insert into T_DIRECT_CHAT
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    MENU_ID, USER_ID, USER_LEVEL, WRITE_TIME, SELECTED_COMPARE_ITEM, CONTENTS_BODY,
    HASH_TAGS, LIKE_COUNT, HATE_COUNT, HIDDEN_YN, REPORT_YN )
Values
  ( 4, 2, 1, 5, 6, 2, 'Branch Node', 'folder',
    3, 'rootID', 313, '2017-03-13 13:31:33', 3, '글내용',
    '해시태그들', 31, 13, 'show', 'N');
COMMIT;