Insert into T_USER_SELECTED_ITEM
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
  USER_CID, MENU_CID, COMPARE_ITEM_CID)
Values
  (1, 0, 0, 1, 8, 0, 'Root Node', 'root',
  '3', 3, 3);
Insert into T_USER_SELECTED_ITEM
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
  USER_CID, MENU_CID, COMPARE_ITEM_CID)
Values
  (2, 1, 0, 2, 7, 1, 'First Child', 'drive',
  '3', 3, 3);
Insert into T_USER_SELECTED_ITEM
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
  USER_CID, MENU_CID, COMPARE_ITEM_CID)
Values
  (3, 2, 0, 3, 4, 2, 'Leaf Node', 'default',
  '3', 3, 3);
Insert into T_USER_SELECTED_ITEM
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
  USER_CID, MENU_CID, COMPARE_ITEM_CID)
Values
  (4, 2, 1, 5, 6, 2, 'Branch Node', 'folder',
  '3', 3, 3);
COMMIT;