version: '3.6'

services:

  guacd:
    image: guacamole/guacd:1.3.0
    hostname: guacd
    ports:
      - "4822:4822"
    environment:
      - GUACD_LOG_LEVEL=debug
    networks: &guacamole-guacd-network
      - guacamole_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]

  guacamole:
    image: guacamole/guacamole:1.3.0
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOSTNAME=192.168.25.40
      - MYSQL_DATABASE=guacamole130
      - MYSQL_USER=root
      - MYSQL_PASSWORD=love0618
      - GUACD_HOSTNAME=guacd
    networks: *guacamole-guacd-network
    depends_on:
      - guacd    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]

networks:
  guacamole_network:
    attachable: true
#networks:
#  guacamole_network:
#    driver: overlay
