version: '3.6'

services:

  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    logging:
          driver: "json-file"
          options:
            max-file: "5"
            max-size: "100m"

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9009:9000"
      - "8008:8000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

networks:
  portainer_network:
    driver: overlay

volumes:
  portainer_data:
