Insert into T_JSTREE_AGGREGATE_RESULT
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT,
   C_LEVEL, C_TITLE, C_TYPE, C_NUMBER_OF_ADVANTAGES, C_LIKE_COUNT, C_TOTAL_REGISTERED_POSTS, C_REGISTERED_HASH_TAG)
Values
  (1, 0, 0, 1, 8,
   0, 'Root Node', 'root', 3, 313, 131, 1);
Insert into T_JSTREE_AGGREGATE_RESULT
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT,
   C_LEVEL, C_TITLE, C_TYPE, C_NUMBER_OF_ADVANTAGES, C_LIKE_COUNT, C_TOTAL_REGISTERED_POSTS, C_REGISTERED_HASH_TAG)
Values
  (2, 1, 0, 2, 7,
   1, 'First Child', 'drive', 3, 313, 131, 1);
Insert into T_JSTREE_AGGREGATE_RESULT
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT,
   C_LEVEL, C_TITLE, C_TYPE, C_NUMBER_OF_ADVANTAGES, C_LIKE_COUNT, C_TOTAL_REGISTERED_POSTS, C_REGISTERED_HASH_TAG)
Values
  (3, 2, 0, 3, 4,
   2, 'Leaf Node', 'default', 3, 313, 131, 1);
Insert into T_JSTREE_AGGREGATE_RESULT
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT,
   C_LEVEL, C_TITLE, C_TYPE, C_NUMBER_OF_ADVANTAGES, C_LIKE_COUNT, C_TOTAL_REGISTERED_POSTS, C_REGISTERED_HASH_TAG)
Values
  (4, 2, 1, 5, 6,
   2, 'Branch Node', 'folder', 3, 313, 131, 1);
COMMIT;
