
Insert into T_JSTREE_AGGREGATE_RESULT
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    TOP_NUMBER_OF_ADVANTAGES, TOP_LIKE_COUNT, TOP_TOTAL_REGISTERED_POSTS, TOP_REGISTERED_HASH_TAG,
    MID_NUMBER_OF_ADVANTAGES, MID_LIKE_COUNT, MID_TOTAL_REGISTERED_POSTS, MID_REGISTERED_HASH_TAG,
    BOT_NUMBER_OF_ADVANTAGES, BOT_LIKE_COUNT, BOT_TOTAL_REGISTERED_POSTS, BOT_REGISTERED_HASH_TAG, TOP_GRAPH_PERCENT,
    MID_GRAPH_PERCENT, BOT_GRAPH_PERCENT, TOP_VERSUS_SCORE, MID_VERSUS_SCORE, BOT_VERSUS_SCORE, TOTAL_TRAFFIC,
    UNIQUE_VISIT, REVISIT_COUNT, PAGE_VIEW, TOTAL_ARTICLE, TOTAL_LIKE_COUNT, TOTAL_SPEC_COUNT, TOTAL_HASH_COUNT,
    STANDARD_ERROR, EQUILIBRIUM_ASSUMPTION, PROBABILITY, LOWER_LIMIT, HIGHER_LIMIT, DISTRIBUTION_T_RESULT)
Values
  (1, 0, 0, 1, 8, 0, 'Root Node', 'root',
   0, 0, 0, 0,
   0, 0, 0, 0,
   0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0);

Insert into T_JSTREE_AGGREGATE_RESULT
  ( C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    TOP_NUMBER_OF_ADVANTAGES, TOP_LIKE_COUNT, TOP_TOTAL_REGISTERED_POSTS, TOP_REGISTERED_HASH_TAG,
    MID_NUMBER_OF_ADVANTAGES, MID_LIKE_COUNT, MID_TOTAL_REGISTERED_POSTS, MID_REGISTERED_HASH_TAG,
    BOT_NUMBER_OF_ADVANTAGES, BOT_LIKE_COUNT, BOT_TOTAL_REGISTERED_POSTS, BOT_REGISTERED_HASH_TAG, TOP_GRAPH_PERCENT,
    MID_GRAPH_PERCENT, BOT_GRAPH_PERCENT, TOP_VERSUS_SCORE, MID_VERSUS_SCORE, BOT_VERSUS_SCORE, TOTAL_TRAFFIC,
    UNIQUE_VISIT, REVISIT_COUNT, PAGE_VIEW, TOTAL_ARTICLE, TOTAL_LIKE_COUNT, TOTAL_SPEC_COUNT, TOTAL_HASH_COUNT,
    STANDARD_ERROR, EQUILIBRIUM_ASSUMPTION, PROBABILITY, LOWER_LIMIT, HIGHER_LIMIT, DISTRIBUTION_T_RESULT)
Values
  (2, 1, 0, 2, 7, 1, 'First Child', 'drive',
   0, 0, 0, 0,
   0, 0, 0, 0,
   0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0);
Insert into T_JSTREE_AGGREGATE_RESULT
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    TOP_NUMBER_OF_ADVANTAGES, TOP_LIKE_COUNT, TOP_TOTAL_REGISTERED_POSTS, TOP_REGISTERED_HASH_TAG,
    MID_NUMBER_OF_ADVANTAGES, MID_LIKE_COUNT, MID_TOTAL_REGISTERED_POSTS, MID_REGISTERED_HASH_TAG,
    BOT_NUMBER_OF_ADVANTAGES, BOT_LIKE_COUNT, BOT_TOTAL_REGISTERED_POSTS, BOT_REGISTERED_HASH_TAG, TOP_GRAPH_PERCENT,
    MID_GRAPH_PERCENT, BOT_GRAPH_PERCENT, TOP_VERSUS_SCORE, MID_VERSUS_SCORE, BOT_VERSUS_SCORE, TOTAL_TRAFFIC,
    UNIQUE_VISIT, REVISIT_COUNT, PAGE_VIEW, TOTAL_ARTICLE, TOTAL_LIKE_COUNT, TOTAL_SPEC_COUNT, TOTAL_HASH_COUNT,
    STANDARD_ERROR, EQUILIBRIUM_ASSUMPTION, PROBABILITY, LOWER_LIMIT, HIGHER_LIMIT, DISTRIBUTION_T_RESULT)
Values
  (3, 2, 0, 3, 4, 2, 'Leaf Node', 'default',
   0, 0, 0, 0,
   0, 0, 0, 0,
   0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0);
Insert into T_JSTREE_AGGREGATE_RESULT
  (C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE,
    TOP_NUMBER_OF_ADVANTAGES, TOP_LIKE_COUNT, TOP_TOTAL_REGISTERED_POSTS, TOP_REGISTERED_HASH_TAG,
    MID_NUMBER_OF_ADVANTAGES, MID_LIKE_COUNT, MID_TOTAL_REGISTERED_POSTS, MID_REGISTERED_HASH_TAG,
    BOT_NUMBER_OF_ADVANTAGES, BOT_LIKE_COUNT, BOT_TOTAL_REGISTERED_POSTS, BOT_REGISTERED_HASH_TAG, TOP_GRAPH_PERCENT,
    MID_GRAPH_PERCENT, BOT_GRAPH_PERCENT, TOP_VERSUS_SCORE, MID_VERSUS_SCORE, BOT_VERSUS_SCORE, TOTAL_TRAFFIC,
    UNIQUE_VISIT, REVISIT_COUNT, PAGE_VIEW, TOTAL_ARTICLE, TOTAL_LIKE_COUNT, TOTAL_SPEC_COUNT, TOTAL_HASH_COUNT,
    STANDARD_ERROR, EQUILIBRIUM_ASSUMPTION, PROBABILITY, LOWER_LIMIT, HIGHER_LIMIT, DISTRIBUTION_T_RESULT)
Values
  (4, 2, 1, 5, 6, 2, 'Branch Node', 'folder',
   0, 0, 0, 0,
   0, 0, 0, 0,
   0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0);
COMMIT;
