/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_JSTREE_COMPARE_SPEC_LOG
(
 C_ID        NUMBER                            NOT NULL,
 C_PARENTID  NUMBER                            NOT NULL,
 C_POSITION  NUMBER                            NOT NULL,
 C_LEFT      NUMBER                            NOT NULL,
 C_RIGHT     NUMBER                            NOT NULL,
 C_LEVEL     NUMBER                            NOT NULL,
 C_TITLE     VARCHAR2(4000 BYTE),
 C_TYPE      VARCHAR2(4000 BYTE),
 C_METHOD    VARCHAR2(4000 BYTE),
 C_STATE     VARCHAR2(4000 BYTE),
 C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_JSTREE_COMPARE_SPEC_LOG IS '기본 트리 스키마 트리거 로그';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC_LOG.C_DATE IS '노드 변경 시';

/*
 * JsTree
 */
CREATE TABLE T_JSTREE_COMPARE_SPEC
(
 C_ID        		NUMBER                            NOT NULL,
 C_PARENTID  	    NUMBER                            NOT NULL,
 C_POSITION  	    NUMBER                            NOT NULL,
 C_LEFT      		NUMBER                            NOT NULL,
 C_RIGHT     		NUMBER                            NOT NULL,
 C_LEVEL     		NUMBER                            NOT NULL,
 C_TITLE     		VARCHAR2(4000 BYTE),
 C_TYPE      		VARCHAR2(4000 BYTE),

    CAL_TIME                    VARCHAR2(4000 BYTE),

    TOP_SPEC_NAME               VARCHAR2(4000 BYTE),

    TOP_SPEC1_TITLE             VARCHAR2(4000 BYTE),
    TOP_SPEC1_AMOUNT            NUMBER,
    TOP_SPEC1_PERCENT           NUMBER,
    TOP_SPEC1_TREND             NUMBER,
    TOP_SPEC1_GRAPH             NUMBER,

    TOP_SPEC2_TITLE             VARCHAR2(4000 BYTE),
    TOP_SPEC2_AMOUNT            NUMBER,
    TOP_SPEC2_PERCENT           NUMBER,
    TOP_SPEC2_TREND             NUMBER,
    TOP_SPEC2_GRAPH             NUMBER,

    TOP_SPEC3_TITLE             VARCHAR2(4000 BYTE),
    TOP_SPEC3_AMOUNT            NUMBER,
    TOP_SPEC3_PERCENT           NUMBER,
    TOP_SPEC3_TREND             NUMBER,
    TOP_SPEC3_GRAPH             NUMBER,

    TOP_SPEC4_TITLE             VARCHAR2(4000 BYTE),
    TOP_SPEC4_AMOUNT            NUMBER,
    TOP_SPEC4_PERCENT           NUMBER,
    TOP_SPEC4_TREND             NUMBER,
    TOP_SPEC4_GRAPH             NUMBER,

    TOP_SPEC5_TITLE             VARCHAR2(4000 BYTE),
    TOP_SPEC5_AMOUNT            NUMBER,
    TOP_SPEC5_PERCENT           NUMBER,
    TOP_SPEC5_TREND             NUMBER,
    TOP_SPEC5_GRAPH             NUMBER,


    MID_SPEC_NAME               VARCHAR2(4000 BYTE),

    MID_SPEC1_TITLE             VARCHAR2(4000 BYTE),
    MID_SPEC1_AMOUNT            NUMBER,
    MID_SPEC1_PERCENT           NUMBER,
    MID_SPEC1_TREND             NUMBER,
    MID_SPEC1_GRAPH             NUMBER,

    MID_SPEC2_TITLE             VARCHAR2(4000 BYTE),
    MID_SPEC2_AMOUNT            NUMBER,
    MID_SPEC2_PERCENT           NUMBER,
    MID_SPEC2_TREND             NUMBER,
    MID_SPEC2_GRAPH             NUMBER,

    MID_SPEC3_TITLE             VARCHAR2(4000 BYTE),
    MID_SPEC3_AMOUNT            NUMBER,
    MID_SPEC3_PERCENT           NUMBER,
    MID_SPEC3_TREND             NUMBER,
    MID_SPEC3_GRAPH             NUMBER,

    MID_SPEC4_TITLE             VARCHAR2(4000 BYTE),
    MID_SPEC4_AMOUNT            NUMBER,
    MID_SPEC4_PERCENT           NUMBER,
    MID_SPEC4_TREND             NUMBER,
    MID_SPEC4_GRAPH             NUMBER,

    MID_SPEC5_TITLE             VARCHAR2(4000 BYTE),
    MID_SPEC5_AMOUNT            NUMBER,
    MID_SPEC5_PERCENT           NUMBER,
    MID_SPEC5_TREND             NUMBER,
    MID_SPEC5_GRAPH             NUMBER,


    BOT_SPEC_NAME               VARCHAR2(4000 BYTE),

    BOT_SPEC1_TITLE             VARCHAR2(4000 BYTE),
    BOT_SPEC1_AMOUNT            NUMBER,
    BOT_SPEC1_PERCENT           NUMBER,
    BOT_SPEC1_TREND             NUMBER,
    BOT_SPEC1_GRAPH             NUMBER,

    BOT_SPEC2_TITLE             VARCHAR2(4000 BYTE),
    BOT_SPEC2_AMOUNT            NUMBER,
    BOT_SPEC2_PERCENT           NUMBER,
    BOT_SPEC2_TREND             NUMBER,
    BOT_SPEC2_GRAPH             NUMBER,

    BOT_SPEC3_TITLE             VARCHAR2(4000 BYTE),
    BOT_SPEC3_AMOUNT            NUMBER,
    BOT_SPEC3_PERCENT           NUMBER,
    BOT_SPEC3_TREND             NUMBER,
    BOT_SPEC3_GRAPH             NUMBER,

    BOT_SPEC4_TITLE             VARCHAR2(4000 BYTE),
    BOT_SPEC4_AMOUNT            NUMBER,
    BOT_SPEC4_PERCENT           NUMBER,
    BOT_SPEC4_TREND             NUMBER,
    BOT_SPEC4_GRAPH             NUMBER,

    BOT_SPEC5_TITLE             VARCHAR2(4000 BYTE),
    BOT_SPEC5_AMOUNT            NUMBER,
    BOT_SPEC5_PERCENT           NUMBER,
    BOT_SPEC5_TREND             NUMBER,
    BOT_SPEC5_GRAPH             NUMBER,

 CONSTRAINT  T_JSTREE_COMPARE_SPEC_PK PRIMARY KEY (C_ID)
 /*
   * CONSTRAINT  T_JSTREE_COMPARE_SPEC_FK1 FOREIGN KEY (OTHER_ID) REFERENCES OTHER T_JSTREE_COMPARE_SPEC(C_ID) ON DELETE CASCADE
   */
);

COMMENT ON TABLE T_JSTREE_COMPARE_SPEC IS '기본 트리 스키마';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.C_TYPE IS '노드 타입';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.CAL_TIME IS '누적 집계 시간';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC_NAME IS '상위 명';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC1_TITLE IS '상위 스펙 1 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC1_AMOUNT IS '상위 스펙 1 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC1_PERCENT IS '상위 스펙 1 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC1_TREND  IS '상위 스펙 1 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC1_GRAPH  IS '상위 스펙 1 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC2_TITLE IS '상위 스펙 2 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC2_AMOUNT IS '상위 스펙 2 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC2_PERCENT IS '상위 스펙 2 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC2_TREND  IS '상위 스펙 2 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC2_GRAPH  IS '상위 스펙 2 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC3_TITLE IS '상위 스펙 3 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC3_AMOUNT IS '상위 스펙 3 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC3_PERCENT IS '상위 스펙 3 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC3_TREND  IS '상위 스펙 3 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC3_GRAPH  IS '상위 스펙 3 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC4_TITLE IS '상위 스펙 4 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC4_AMOUNT IS '상위 스펙 4 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC4_PERCENT IS '상위 스펙 4 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC4_TREND  IS '상위 스펙 4 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC4_GRAPH  IS '상위 스펙 4 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC5_TITLE IS '상위 스펙 5 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC5_AMOUNT IS '상위 스펙 5 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC5_PERCENT IS '상위 스펙 5 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC5_TREND  IS '상위 스펙 5 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.TOP_SPEC5_GRAPH  IS '상위 스펙 5 그래프';


COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC_NAME   IS '중위 명';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC1_TITLE IS '중위 스펙 1 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC1_AMOUNT IS '중위 스펙 1 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC1_PERCENT IS '중위 스펙 1 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC1_TREND  IS '중위 스펙 1 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC1_GRAPH  IS '중위 스펙 1 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC2_TITLE IS '중위 스펙 2 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC2_AMOUNT IS '중위 스펙 2 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC2_PERCENT IS '중위 스펙 2 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC2_TREND  IS '중위 스펙 2 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC2_GRAPH  IS '중위 스펙 2 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC3_TITLE IS '중위 스펙 3 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC3_AMOUNT IS '중위 스펙 3 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC3_PERCENT IS '중위 스펙 3 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC3_TREND  IS '중위 스펙 3 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC3_GRAPH  IS '중위 스펙 3 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC4_TITLE IS '중위 스펙 4 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC4_AMOUNT IS '중위 스펙 4 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC4_PERCENT IS '중위 스펙 4 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC4_TREND  IS '중위 스펙 4 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC4_GRAPH  IS '중위 스펙 4 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC5_TITLE IS '중위 스펙 5 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC5_AMOUNT IS '중위 스펙 5 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC5_PERCENT IS '중위 스펙 5 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC5_TREND  IS '중위 스펙 5 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.MID_SPEC5_GRAPH  IS '중위 스펙 5 그래프';


COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC_NAME   IS '하위 명 ';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC1_TITLE IS '하위 스펙 1 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC1_AMOUNT IS '하위 스펙 1 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC1_PERCENT IS '하위 스펙 1 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC1_TREND  IS '하위 스펙 1 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC1_GRAPH  IS '하위 스펙 1 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC2_TITLE IS '하위 스펙 2 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC2_AMOUNT IS '하위 스펙 2 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC2_PERCENT IS '하위 스펙 2 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC2_TREND  IS '하위 스펙 2 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC2_GRAPH  IS '하위 스펙 2 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC3_TITLE IS '하위 스펙 3 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC3_AMOUNT IS '하위 스펙 3 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC3_PERCENT IS '하위 스펙 3 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC3_TREND  IS '하위 스펙 3 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC3_GRAPH  IS '하위 스펙 3 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC4_TITLE IS '하위 스펙 4 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC4_AMOUNT IS '하위 스펙 4 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC4_PERCENT IS '하위 스펙 4 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC4_TREND  IS '하위 스펙 4 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC4_GRAPH  IS '하위 스펙 4 그래프';

COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC5_TITLE IS '하위 스펙 5 이름';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC5_AMOUNT IS '하위 스펙 5 개수';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC5_PERCENT IS '하위 스펙 5 점유율';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC5_TREND  IS '하위 스펙 5 변화량';
COMMENT ON COLUMN T_JSTREE_COMPARE_SPEC.BOT_SPEC5_GRAPH  IS '하위 스펙 5 그래프';

/*
 * 인덱스는 되도록 걸지 말것.
 * CREATE UNIQUE INDEX I_COMPREHENSIVETREE ON T_JSTREE_COMPARE_SPEC
 *      ("C_ID" ASC)
 * DROP SEQUENCE S_JSTREE_COMPARE_SPEC;
 */


CREATE SEQUENCE S_JSTREE_COMPARE_SPEC
 START WITH 10
 MAXVALUE 999999999999999999999999999
 MINVALUE 0
 NOCYCLE
 CACHE 20
 NOORDER;

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER "TG_JSTREE_COMPARE_SPEC"
BEFORE DELETE OR INSERT OR UPDATE
ON T_JSTREE_COMPARE_SPEC
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;
/******************************************************************************
   NAME:       TRIGGER_COMPREHENSIVETREE
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        2012-08-29             1. Created this trigger.

   NOTES:

   Automatically available Auto Replace Keywords:
      Object Name:     TRIGGER_COMPREHENSIVETREE
      Sysdate:         2012-08-29
      Date and Time:   2012-08-29, 오후 5:26:44, and 2012-08-29 오후 5:26:44
      Username:         (set in TOAD Options, Proc Templates)
      Table Name:      T_JSTREE_COMPARE_SPEC (set in the "New PL/SQL Object" dialog)
      Trigger Options:  (set in the "New PL/SQL Object" dialog)
******************************************************************************/
BEGIN
  tmpVar := 0;
   IF UPDATING  THEN
       insert into T_JSTREE_COMPARE_SPEC_LOG
       values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);
       insert into T_JSTREE_COMPARE_SPEC_LOG
       values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);
    END IF;
   IF DELETING THEN
       insert into T_JSTREE_COMPARE_SPEC_LOG
       values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
   END IF;
   IF INSERTING  THEN
       insert into T_JSTREE_COMPARE_SPEC_LOG
       values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
   END IF;

  EXCEPTION
    WHEN OTHERS THEN
      -- Consider logging the error and then re-raise
      RAISE;
END TG_JSTREE_COMPARE_SPEC;

/**
PK - FK
**/
ALTER TABLE T_JSTREE_MENU ADD(
  CONSTRAINT T_JSTREE_MENU_FK_CS
 FOREIGN KEY (COMPARE_SPEC_ID)
 REFERENCES T_JSTREE_COMPARE_SPEC (C_ID));
/