CREATE TABLE T_M_MENU_DIRECTCHAT
(
  MENU_CID        NUMBER,
  DIRECTCHAT_CID  NUMBER
);

CREATE TABLE T_M_MENU_COMPAREITEM
(
  MENU_CID         NUMBER,
  COMPAREITEM_CID  NUMBER
);

CREATE TABLE T_M_COMPAREITEM_SPECHASHTAG
(
  COMPAREITEM_CID  NUMBER,
  SPECHASHTAG_CID  NUMBER
);